### ISSUE TITLE
cannot render pdf design properly

### ISSUE THREAD

**Issue by murali129** [Novaleaf/phantomjscloud-node#10]
when I tried to generate the pdf for http://foundation.zurb.com/ where this is the [API request ](https://phantomjscloud.com/api/browser/v2/a-demo-key-with-low-quota-per-ip-address/?request={url:"http://foundation.zurb.com/",renderType:"pdf"}) from phantomjscloud website to generate pdf from html, the pdf design is completely corrupted. Also the same problem with websites that use bootstrap like https://bootswatch.com/paper/  [pdf image](https://phantomjscloud.com/api/browser/v2/a-demo-key-with-low-quota-per-ip-address/?request={url:%22https://bootswatch.com/paper/%22,renderType:%22pdf%22}) and also with topcoat http://topcoat.io/topcoat/topcoat-mobile-light.html [pdf image](https://phantomjscloud.com/api/browser/v2/a-demo-key-with-low-quota-per-ip-address/?request={url:%22http://topcoat.io/topcoat/topcoat-mobile-light.html%22,renderType:%22png%22})

**Comment by jasonswearingen** [comment]
hello the issue is that we use phantomjs 2.1.1, and I assume the zurb site uses flexbox or some other fancy element that's not compatible.

However!  We are upgrading PhantomJsCloud to include PhantomJs 2.5Beta and the pdf renders fine with that.

once that gets deployed, I will update the npm package and let you know.  It should be ready tomorrow.

**Comment by murali129** [comment]
that should be great, thanks

**Comment by jasonswearingen** [comment]
hi you can now use the phantomjs 2.5Beta to render pdf's more or less properly.  here's an example:

https://phantomjscloud.com/api/browser/v2/a-demo-key-with-low-quota-per-ip-address/?request={pages:[{url:%22http://foundation.zurb.com/%22,renderType:%22pdf%22,}],backend:%22beta%22}

though FYI pdf's in 2.5beta are missing some features like page breaks and headers+footers.
