### ISSUE TITLE
Feature request: send output to AWS S3 bucket

### ISSUE THREAD

**Issue by hypersurge** [Novaleaf/phantomjscloud-node#11]
Suggestion:

IPageRequest.outputToS3:string;

If string is present use it as a S3 presigned url, and send the output there instead of returning in request.

https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html

This is beneficial for bulk rendering that needs to be cached, may reduce response latency, bandwidth for consuming service.

**Comment by jasonswearingen** [comment]
sorry this won't be considered until the next major upgrade (in progress)
