### ISSUE TITLE
Notification:  NOTICE: Longjohn is known to cause CPU usage .. because of xlib

### ISSUE THREAD

**Issue by a-tonchev** [Novaleaf/phantomjscloud-node#14]
When I start my node server I get this notification:

NOTICE: Longjohn is known to cause CPU usage due to its extensive data collection during runtime.
It generally should not be used in production applications.

After analyzing it comes out that it is from the xlib dependancy of the phantomjscloud.

Maybe is it posisble to replace this library?

**Comment by jasonswearingen** [comment]
yes, I'm surprised about this, I don't think we actually used longjohn in any version of xlib.      Can you let me know your xlib version  (or PhantomJsCloud) so I can investigate further and fix?  If not I'll assume you are using the latest version of the ```phantomjscloud-node``` package and will investigate that in the next few days

**Comment by a-tonchev** [comment]
@jasonswearingen my version is 3.5.5 I think that is the newest version. To see the error message you need to run the project in production environment (NODE_ENV=production)

**Comment by Just-Ghali** [comment]
I can confirm this issue on v 3.5.5, xlib version 16.5.0, requires "longjohn": "^0.2.12",

**Comment by jasonswearingen** [comment]
Hi, sorry about the delay on getting this fixed.  I am finishing up a basic rewrite of the dependency ```xlib``` and have been delayed with other issues for the last few weeks.  I should be able to get this taken care of around this weekend.

**Comment by jasonswearingen** [comment]
hi just a fyi that I'm actively working on this now.
