### ISSUE TITLE
Example for doing a POST request

### ISSUE THREAD

**Issue by stockholmux** [Novaleaf/phantomjscloud-node#4]
I'm trying to do a post request to a website with this module and I can't quite figure out the correct correct settings. Could you provide an example?

**Comment by jasonswearingen** [comment]
hi, here is an example that does a POST:


`
        var phantomJsCloud = require("phantomjscloud");
        var browser = new phantomJsCloud.BrowserApi();

        browser.requestSingle(
              { url: "https://phantomjscloud.com/examples/helpers/requestdata",
              renderType: "plainText",
              urlSettings: { operation: "POST" },  
              }
              , (err, userResponse) => {
            //can use a callback like this example, or a Promise (see the Typescript example below)
            if (err != null) {
                throw err;
            }
            console.log(JSON.stringify(userResponse.content));
        });
`
