### ISSUE TITLE
Version 2 breaks on node 4

### ISSUE THREAD

**Issue by stockholmux** [Novaleaf/phantomjscloud-node#6]
I was running this module with Node 4 successfully in Nov/Dec of 2016 and shelved the project. I came back and tried to run my scripts today and I got a error message about the certificate not being trusted. I saw a new version was released and upgraded the `phantomjscloud-node` module to the latest (was running on v1.0.14, upgraded to 2) then I got a syntax error in `xlib`. I upgraded to Node 6 and I was able to finally get my scripts running again. It would be nice if the node engine compatibility was in package.json or if the service maintained backward compatibility with the older libraries. It would help me not wanting to set my hair on fire while debugging.

**Comment by jasonswearingen** [comment]
Hi, sorry about that.  the problem is one of the xlib dependencies, probably google cloud tools.  I have created a tracking issue in the ```xlib``` project to get this fixed, but it will be a week or two.
