### ISSUE TITLE
Phantomjscloud not working with aws lambda nodejs

### ISSUE THREAD

**Issue by murali129** [Novaleaf/phantomjscloud-node#8]
[link to my question on stackoverlfow](http://stackoverflow.com/questions/42850980/phantomjscloud-not-working-with-aws-lambda-nodejs)

The code is working good in my local environment but when I deploy it to aws lambda it is showing problems, but is working good when I deploy to Google cloud functions, I suspect the problem might be with AWS, so please tell me if some one have got this issue before

The below error is being thrown when I include **require('phantomjscloud')**  in my code
```
{
  "errorMessage": "callback called with Error argument, but there was a problem while retrieving one or more of its message, name, and stack"
}
```
also it is showing a syntax error in index.js 
**START RequestId: 7260c7a9-0adb-11e7-b923-aff6d9a52d2d Version: $LATEST Syntax error in module 'index': SyntaxError END RequestId: 7260c7a9-0adb-11e7-b923-aff6d9a52d2d**

**Comment by jasonswearingen** [comment]
Hi I actually saw your stackoverflow question before this.

I have a feeling that one of the sub-libraries from our main utility
library (xlib) is not compatable with old versions of node.  I'm in charge
of the phantomjscloud npm library so I will investigate this today.

FYI if you are in a rush, you don't need to use our npm library, and can
instead code against the http(s) endpoints directly.  But I will get this
working today, and if I can't figure it out, I will publish a
"phantomjscloud-lite" module that doesn't include any library dependencies.

I'll email you when I have some news, sometime today I think, but if not,
tomorrow (saturday)

 - Jason

**Comment by murali129** [comment]
It's seems your reasoning is correct, that is why it is working with Google cloud functions which uses node version 6.9.2.

**Comment by jasonswearingen** [comment]
any chance you can upgrade to 6.x?  if not, no worries, I will still work on tracking down the offending sub-library and replace it with something more flexible.

**Comment by jasonswearingen** [comment]
can you tell me what version of node you are running?  so I can verify my fix works with it

**Comment by murali129** [comment]
aws lambda by default provides node 4.3 runtime environment, we cannot change it, that it where the problem has come

**Comment by jasonswearingen** [comment]
OK i am going to start working on this within the Hour, should have a fix
deployed soon


- Sent from my mobile

**Comment by jasonswearingen** [comment]
Hi, can you please try now? (with a clean npm install of the latest ```phantomjscloud``` npm package)

i made some changes to make the ```xlib``` library (a dependency) compatable and have verified it works with node 4.2 and npm 2.14

**Comment by murali129** [comment]
It is working now, thanks for fixing it.
